src/dataprotector/Controllers/SecureRecordRetrieveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using dataprotector.Data;
using dataprotector.Models;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace dataprotector.Controllers
{
    public class SecureRecordRetrieveController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IDataProtector _protector;

        public SecureRecordRetrieveController(ApplicationDbContext db, IDataProtectionProvider provider)
        {
            this._db = db;
            this._protector = provider.CreateProtector("web-encrypt-decrypt");
        }

        // GET: /<controller>/
        [HttpGet]
        [Route("record/{recordId}")]
        public IActionResult Index(int recordId)
        {
            // Query for the record
            var result = from record in _db.SecureRecords
                where record.RecordId == recordId
                select record;
            SecureRecord secureRecord = result.First();

            // Decrypt
            secureRecord.FirstName = _protector.Unprotect(secureRecord.FirstName);
            secureRecord.LastName = _protector.Unprotect(secureRecord.LastName);
            secureRecord.CreditCardNo = _protector.Unprotect(secureRecord.CreditCardNo);

            return View(secureRecord);
        }
    }
}

src/dataprotector/Controllers/SecureRecordSubmitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using dataprotector.Data;
using dataprotector.Models;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace dataprotector.Controllers
{
    public class SecureRecordSubmitController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IDataProtector _protector;

        public SecureRecordSubmitController(ApplicationDbContext db, IDataProtectionProvider provider)
        {
            this._db = db;
            this._protector = provider.CreateProtector("web-encrypt-decrypt");
        }

        // GET: /<controller>/
        [HttpGet]
        public IActionResult Index()
        {
            SecureRecord secureRecord = new SecureRecord();
            return View(secureRecord);
        }

        [HttpPost]
        public IActionResult Index(SecureRecord secureRecord)
        {
            // Encrypt
            secureRecord.FirstName = _protector.Protect(secureRecord.FirstName);
            secureRecord.LastName = _protector.Protect(secureRecord.LastName);
            secureRecord.CreditCardNo = _protector.Protect(secureRecord.CreditCardNo);

            // Save to the database
            this._db.SecureRecords.Add(secureRecord);
            this._db.SaveChanges();

            return RedirectToAction("Success");
        }

        public IActionResult Success()
        {
            return View();
        }
    }
}

src/dataprotector/Views/SecureRecordRetrieve/Index.cshtml
@model dataprotector.Models.SecureRecord
@using Microsoft.AspNetCore.Mvc.Rendering

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>Your page title here :)</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- FONT
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="/css/normalize.css">
    <link rel="stylesheet" href="/css/skeleton.css">
    <!-- Favicon
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="icon" type="image/png" href="/images/favicon.png">
    
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <!-- Primary Page Layout
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
<div class="container">
    <form asp-action="Index" asp-controller="SecureRecordSubmit" method="post" role="form">
        <h1>Secure Form</h1>
        <div class="row">
            <p><strong>First Name</strong>: @Html.DisplayFor(model => model.FirstName)</p>
        </div>
        <div class="row">
            <p><strong>Last Name</strong>: @Html.DisplayFor(model => model.LastName)</p>
        </div>
        <div class="row">
            <p><strong>Credit Card</strong>: @Html.DisplayFor(model => model.CreditCardNo)</p>
        </div>
    </form>
</div>
    <!-- End Document
      –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>
</html>